.github/workflows/pr.yml, .gitignore, CHANGELOG.md, Controllers/ProjectOverview.php, Middleware/GetLanguageAssets.php, README.md, Repositories/ProjectOverview.php, composer.json, composer.lock, phpstan.dist.neon, register.php
https://leantime.itkdev.dk/#/tickets/showTicket/2195
* Added compatability for Leantime 3.2
* Change imports
* Replace old session handling with new session handling, 
* Update leantime dependency for phpstan
* Add composer.lock
* Update from php8.1 -> php 8.3 in pr.yml and README
N/A
=> feature/2195 leantime 3.2 compatible

CHANGELOG.md, register.php
https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/2195
- readded what I accidentally removed from the [last pr](https://github.com/ITK-Leantime/project-overview/pull/11)
=> 2195: add request uri api check

CHANGELOG.md, composer.json
=> Release 2.0.1

CHANGELOG.md, composer.json
=> Release 2.0.2

CHANGELOG.md, register.php
https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/2195
Remove urlencode in register, as this does not work...
=> 2195: remove urlencode in register

CHANGELOG.md, composer.json
=> Release 2.0.3

CHANGELOG.md, composer.json
=> Release 2.1.0

CHANGELOG.md, composer.json
=> Release 2.1.1

CHANGELOG.md, Repositories/ProjectOverview.php
N/A
Added explicit null check to get all projects, since null cannot be matched with comparison operators
N/A
=> Hotfix: Minor sql oversigt

CHANGELOG.md, composer.json
=> Release 2.1.2

CHANGELOG.md, Controllers/ProjectOverview.php, Templates/projectOverview.blade.php, assets/project-overview.css, assets/project-overview.js
[2765](https://leantime.itkdev.dk/dashboard/show#/tickets/showTicket/2765)
Fixed status and priority selectors that is unfortunately broke at an earlier stage.
Removed colouring of milestones (due to repeating issue with white text on white background)
N/A
=> 2765: fix priory and status selectors

CHANGELOG.md, composer.json
=> Release 2.1.3

CHANGELOG.md, Controllers/ProjectOverview.php, Repositories/ProjectOverview.php, Services/ProjectOverview.php, Templates/projectOverview.blade.php
N/A
Removed part in template where milestone color from database is set, as i missed it in the first round.
N/A
=> hotfix: removing existing colors

CHANGELOG.md, composer.json
=> Release 2.1.4

CHANGELOG.md, Repositories/ProjectOverview.php
N/A
Paranthesized search field sql, to ensure it still working with user filter active.
N/A
=> hotfix: fix searching with user filter active

CHANGELOG.md, composer.json
=> Release 2.1.5

CHANGELOG.md, Controllers/ProjectOverview.php, README.md, Templates/projectOverview.blade.php, assets/project-overview.css, composer.json
[#3238](https://leantime.itkdev.dk/#/tickets/showTicket/3238)
Reordered filters
N/A
=> Minor changes and bugfixes

CHANGELOG.md, composer.json
=> Release 2.2.1

CHANGELOG.md, composer.json
=> Release 2.3.0

CHANGELOG.md, Templates/projectOverview.blade.php
N/A
Corrected header of priority
N/A
=> Hotfix: Correcting priority header

CHANGELOG.md
=> Release 3.0.2

CHANGELOG.md, composer.json
=> Release 3.0.3

CHANGELOG.md, composer.json
=> Release 3.1.0

CHANGELOG.md, Repositories/ProjectOverview.php
[#49]
Previous PR was based on a version of the code base that coincidently implemented functions used. 
This PR downgrades the required method use to make it work with the current version of the code base.
N/A
=> hotfix: downgrade functionality requirements

CHANGELOG.md, composer.json
=> Release 3.1.1

CHANGELOG.md, Repositories/ProjectOverview.php, Templates/projectOverview.blade.php, assets/project-overview.css
N/A
Displays who has logged time on a specific ticket, when hovering over the total amount of hours logged.
=> Feature: Specified logged time on hover

CHANGELOG.md, composer.json
=> Release 3.3.0

CHANGELOG.md, Controllers/ProjectOverview.php, Taskfile.yml, Templates/projectOverview.blade.php, assets/project-overview.css
N/A
Projectname below ticketname is now a link to the project dashboard.
Styling: Status and priority selects are now full width of their columns.
=> Feature: Feature: Project name as link

CHANGELOG.md, Templates/projectOverview.blade.php, assets/project-overview.css
N/A
Minor visuals + filter out selected status and priority.
N/A
=> Hotfix: minor visual adjustments
